# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('exam_id', models.AutoField(primary_key=True, serialize=False)),
                ('weight', models.CharField(max_length=200)),
                ('temperature', models.CharField(max_length=200)),
                ('blood_pressure', models.CharField(max_length=20)),
                ('respiration', models.CharField(max_length=20)),
                ('heart_rate', models.CharField(max_length=20)),
                ('reflex', models.CharField(max_length=20)),
                ('visual_activity', models.CharField(max_length=20)),
                ('ears', models.CharField(max_length=20)),
                ('skin_polar', models.CharField(max_length=20)),
                ('lungs', models.CharField(max_length=20)),
                ('throat', models.CharField(max_length=20)),
                ('interview_note', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
