# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 04:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_appointment_doctor_id'),
        ('examination', '0002_auto_20170506_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='app_id',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='appointment.Appointment'),
        ),
    ]
