# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 04:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_patient_date'),
        ('examination', '0003_examination_app_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='patient_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='patient.Patient'),
        ),
    ]
