# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 23:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0009_appointment_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='username',
            new_name='user',
        ),
    ]
