# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 00:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0010_auto_20170509_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='patient_id',
        ),
    ]
