# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 10:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0011_remove_appointment_patient_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='date',
        ),
    ]
