# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=200)),
                ('mname', models.CharField(max_length=200)),
                ('lname', models.CharField(max_length=200)),
                ('dob', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=20)),
                ('addr1', models.CharField(max_length=20)),
                ('addr2', models.CharField(max_length=20)),
                ('addr3', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('county', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('zipcode', models.CharField(max_length=20)),
                ('phone1', models.CharField(max_length=20)),
                ('phone2', models.CharField(max_length=20)),
                ('phone3', models.CharField(max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
