# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 06:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0003_auto_20170505_1943'),
        ('doctor', '0001_initial'),
        ('appointment', '0007_appointment_doctor_id'),
        ('examination', '0003_examination_app_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('diagnosis_id', models.AutoField(primary_key=True, serialize=False)),
                ('weight', models.CharField(max_length=200)),
                ('temperature', models.CharField(max_length=200)),
                ('blood_pressure', models.CharField(max_length=20)),
                ('respiration', models.CharField(max_length=20)),
                ('heart_rate', models.CharField(max_length=20)),
                ('reflex', models.CharField(max_length=20)),
                ('visual_activity', models.CharField(max_length=20)),
                ('ears', models.CharField(max_length=20)),
                ('skin_polar', models.CharField(max_length=20)),
                ('lungs', models.CharField(max_length=20)),
                ('throat', models.CharField(max_length=20)),
                ('interview_note', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('app_id', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='appointment.Appointment')),
                ('doctor_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='doctor.Doctor')),
                ('exam_id', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='examination.Examination')),
            ],
        ),
        migrations.CreateModel(
            name='Icd10Code',
            fields=[
                ('icd10code', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='icd10Code',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='diagnosis.Icd10Code'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='patient_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='patient.Patient'),
        ),
    ]
