# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icd10code',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
