# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0003_auto_20170510_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='confirm',
            field=models.CharField(default=2, max_length=1),
            preserve_default=False,
        ),
    ]
