# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0004_diagnosis_confirm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='confirm',
            field=models.CharField(default='N', max_length=1),
        ),
    ]
